---                                                                                                                       
apiVersion: apps/v1                                                                                                       
kind: Deployment                                                                                                          
metadata:                                                                                                                 
  labels:                                                                                                                 
    app: nagios                                                                                                           
  name: nagios-deployment                                                                                                 
spec:                                                                                                                     
  replicas: 1                                                                                                             
  selector:                                                                                                               
    matchLabels:                                                                                                          
      app: nagios                                                                                                         
  template:                                                                                                               
    metadata:                                                                                                             
      labels:                                                                                                             
        app: nagios                                                                                                       
    spec:                                                                                                                 
      containers:                                                                                                         
      - name: nagios-container                                                                                            
        image: jasonrivers/nagios                                                                                         
        ports:                                                                                                            
        - containerPort: 80                                                                                               
---                                                                                                                       
apiVersion: v1                                                                                                            
kind: Service                                                                                                             
metadata:                                                                                                                 
  name: nagios-service                                                                                                    
spec:                                                                                                                     
  ports:                                                                                                                  
    - name: http                                                                                                          
      port: 80                                                                                                            
      nodePort: 30008                                                                                                     
      protocol: TCP                                                                                                       
  selector:         
    app: nagios                                                                                                           
  type: NodePort
